-- bootstrap.lua: Safe bootstrap for Neovim config with lazy.nvim and graceful errors
-- Generated by ChatGPT on 2025-10-29 (Asia/Bangkok)

-- 1) leader must be set before any plugins
vim.g.mapleader = ' ' 
vim.g.maplocalleader = ' ' 

-- 2) speed up startup (Neovim >=0.9)
pcall(function() vim.loader.enable() end)

-- 3) recommended UI/basic settings that are harmless even if duplicated
vim.opt.termguicolors = true
vim.opt.number = true
vim.opt.relativenumber = false
vim.opt.mouse = 'a'

-- 4) Disable netrw when using nvim-tree or similar
-- (safe even if you don't use nvim-tree)
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1

-- 5) Auto bootstrap lazy.nvim if missing
local lazypath = vim.fn.stdpath('data') .. '/lazy/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ 'git', 'clone', '--filter=blob:none',
    'https://github.com/folke/lazy.nvim.git', '--branch=stable', lazypath })
end
vim.opt.rtp:prepend(lazypath)

-- 6) Safe require helper: returns nil + message instead of throwing
local function safe_require(mod)
  local ok, res = pcall(require, mod)
  if not ok then
    vim.schedule(function()
      vim.notify(('⚠️  Failed to load %s: %s'):format(mod, res), vim.log.levels.WARN)
    end)
    return nil
  end
  return res
end

-- 7) Load your modules if they exist.
--    Expected layout (adjust if your repo uses a different structure):
--      lua/core/*.lua           -- options, keymaps, autocmds
--      lua/plugins/init.lua     -- list of plugins (lazy spec)
--      lua/plugins/config/*.lua -- per-plugin configs (optional)

-- core (won't crash if missing)
safe_require('core.options')
safe_require('core.keymaps')
safe_require('core.autocmds')

-- plugins spec (fall back to minimal safe defaults if missing)
local plugin_spec = safe_require('plugins')
if not plugin_spec then
  plugin_spec = {
    { 'nvim-lua/plenary.nvim' },
    { 'nvim-tree/nvim-web-devicons', opts = {} },
  }
end

-- 8) Setup lazy with defensive defaults
local ok_lazy, lazy = pcall(require, 'lazy')
if ok_lazy then
  lazy.setup(plugin_spec, {
    change_detection = { notify = false },
    checker = { enabled = false },
    install = { colorscheme = { 'habamax', 'default' } },
    ui = { wrap = true },
  })
else
  vim.schedule(function()
    vim.notify('lazy.nvim not found or failed to load. Plugins disabled for this session.', vim.log.levels.WARN)
  end)
end

-- 9) Final sanity checks / messages
vim.schedule(function()
  if vim.fn.has('nvim-0.9') == 0 then
    vim.notify('Neovim >= 0.9 is recommended for this config.', vim.log.levels.INFO)
  end
end)
